# Generated by Django 3.1.6 on 2021-02-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='yt_link',
            field=models.URLField(default='https://youtube.com'),
            preserve_default=False,
        ),
    ]
